### PR TITLE
news update- sc15

### PR DESCRIPTION
**Pull request by htroyer**

### CODE REVIEW

**Comment by htroyer** [comment]
@philloooo More edits completed.  Can you review today?

**Comment by philloooo** [comment]
so i made several edit on this branch. Can you pull the latest and check if
the pdf works as expected?

**Comment by htroyer** [comment]
Ok, the rest of my changes are done.  Ready to merge @philloooo

**Comment by philloooo** [comment]
looks good! Merged and pushed to amazon

**Pull request merged**
